### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by kuroitenshi9** [PyrkiTeam/HabitHero#3]
Create the diagram for the classes based on the class documentation above [ class documentation.](https://docs.google.com/document/d/1c5EORxQdkdbQSzPlpQz1Cc8Hk_MeyrAaOWdza-KWlYE/edit?usp=sharing)

**Comment by ritaly** [comment]
MIRO: 
https://miro.com/app/board/uXjVKGUdQrk=/
